name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  publish:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Install dependencies
        working-directory: qrradoc
        run: npm ci

      - name: Build Docusaurus
        working-directory: qrradoc
        run: npm run build

      - name: Publish to GitHub Pages
        uses: rayluo/github-pages-overwriter@v1.3
        with:
          source-directory: qrradoc/build
          target-branch: gh-pages
